import { BarChart2 } from 'lucide-react'
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import { motion, AnimatePresence } from 'framer-motion'
import type { LabelMode, TaxonomyLevel } from '../types'
import { CHART_COLORS } from '../theme'

interface VolumeEntry {
  date: string
  alerts: number
  sars: number
  inferred: number
}

interface Props {
  data: Record<TaxonomyLevel, VolumeEntry[]>
  selectedLevel: TaxonomyLevel
  levelLabel: string
  labelMode: LabelMode
}

const LEVEL_DISPLAY: Record<TaxonomyLevel, string> = {
  l1: 'L1',
  l2: 'L2',
  l3: 'L3',
  global: 'Global',
}

function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; name: string; color: string }>; label?: string }) {
  if (!active || !payload) return null
  return (
    <div className="bg-white border border-(--color-border) rounded-lg px-3 py-2 shadow-xl">
      <div className="text-[10px] text-gray-400 mb-1 font-mono">{label}</div>
      {payload.map((entry, i) => (
        <div key={i} className="flex items-center gap-2 text-[11px]">
          <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: entry.color }} />
          <span className="text-gray-500">{entry.name}:</span>
          <span className="font-mono text-gray-700">{entry.value}</span>
        </div>
      ))}
    </div>
  )
}

export function VolumeChart({ data, selectedLevel, levelLabel, labelMode }: Props) {
  const showInferred = labelMode === 'formal_inferred'
  const activeData = data[selectedLevel]

  const tickFormatter = (value: string, index: number) => {
    if (index % 7 !== 0) return ''
    return value.slice(5)
  }

  return (
    <div className="rounded-xl border border-(--color-border) bg-(--color-surface) p-5">
      <div className="flex items-center gap-2 mb-1">
        <BarChart2 className="w-3.5 h-3.5 text-gray-400" />
        <span className="text-[10px] uppercase tracking-wider text-gray-600 font-semibold">
          Marginal Alert Volume
        </span>
        <span className="text-[9px] font-mono text-gray-400 bg-black/[0.04] rounded-full px-1.5 py-0.5">
          {LEVEL_DISPLAY[selectedLevel]} — {levelLabel}
        </span>
      </div>
      <p className="text-[10px] text-gray-400 mb-4">
        Additional alerts generated by this rule beyond the {levelLabel} peer group
      </p>

      <AnimatePresence mode="wait">
        <motion.div
          key={selectedLevel}
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -4 }}
          transition={{ duration: 0.2 }}
          className="h-[260px]"
        >
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={activeData} margin={{ top: 5, right: 5, bottom: 20, left: 5 }}>
              <defs>
                <linearGradient id="gradAlerts" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor={CHART_COLORS.indigo} stopOpacity={0.2} />
                  <stop offset="95%" stopColor={CHART_COLORS.indigo} stopOpacity={0} />
                </linearGradient>
                <linearGradient id="gradSars" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor={CHART_COLORS.violet} stopOpacity={0.2} />
                  <stop offset="95%" stopColor={CHART_COLORS.violet} stopOpacity={0} />
                </linearGradient>
                <linearGradient id="gradInferred" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor={CHART_COLORS.violetLight} stopOpacity={0.2} />
                  <stop offset="95%" stopColor={CHART_COLORS.violetLight} stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid stroke={CHART_COLORS.grid} strokeDasharray="3 3" vertical={false} />
              <XAxis
                dataKey="date"
                tick={{ fill: CHART_COLORS.axis, fontSize: 11 }}
                tickFormatter={tickFormatter}
                angle={-35}
                textAnchor="end"
                axisLine={{ stroke: CHART_COLORS.grid }}
                tickLine={false}
              />
              <YAxis
                tick={{ fill: CHART_COLORS.axis, fontSize: 11 }}
                axisLine={false}
                tickLine={false}
                width={40}
              />
              <Tooltip content={<CustomTooltip />} />
              <Area
                type="monotone"
                dataKey="alerts"
                name="Marginal Alerts"
                stroke={CHART_COLORS.indigo}
                fill="url(#gradAlerts)"
                strokeWidth={1.5}
              />
              <Area
                type="monotone"
                dataKey="sars"
                name="Marginal SARs"
                stroke={CHART_COLORS.violet}
                fill="url(#gradSars)"
                strokeWidth={1.5}
              />
              {showInferred && (
                <Area
                  type="monotone"
                  dataKey="inferred"
                  name="Marginal Inferred"
                  stroke={CHART_COLORS.violetLight}
                  fill="url(#gradInferred)"
                  strokeWidth={1.5}
                />
              )}
            </AreaChart>
          </ResponsiveContainer>
        </motion.div>
      </AnimatePresence>
    </div>
  )
}
